version: 2.1

jobs:
  build-and-deploy:
    working_directory: ~/cedar-groves-site
    docker:
      - image: circleci/node:14.16
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -y awscli
      - setup_remote_docker
      - run:
          name: Docker Login
          command: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR
      - run:
          name: Build
          command: |
            docker build -t $DOCKER_CONTAINER_NAME .
            docker tag $DOCKER_CONTAINER_NAME:latest $ECR/$DOCKER_CONTAINER_NAME:latest
            docker push $ECR/$DOCKER_CONTAINER_NAME:latest
      - deploy:
          name: Deploy
          command: |
            ssh -i $SSH_KEY $EC2_INSTANCE_USERNAME@$EC2_INSTANCE_IP_ADDRESS 'docker pull $ECR/$DOCKER_CONTAINER_NAME:latest && docker stop $DOCKER_CONTAINER_NAME && docker rm $DOCKER_CONTAINER_NAME && docker run -d -p $DOCKER_HOST_PORT:$PORT --name $DOCKER_CONTAINER_NAME $ECR/$DOCKER_CONTAINER_NAME:latest'
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main
