version: 2.1

jobs:
  build-and-deploy:
    working_directory: ~/cedar-groves-site
    docker:
      - image: circleci/node:14.16
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -y awscli
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker login --username AWS -p $(aws ecr get-login-password --region $AWS_REGION) $ECR_REPOSITORY            
            docker build -t $DOCKER_CONTAINER_NAME .
            docker tag $DOCKER_CONTAINER_NAME:latest $ECR_REPOSITORY:latest
            docker push $ECR_REPOSITORY:latest
      - deploy:
          name: Deploy to EC2 instance
          command: |
            ssh -i $SSH_KEY $EC2_INSTANCE_USERNAME@$EC2_INSTANCE_IP_ADDRESS 'docker pull $ECR_REPOSITORY:latest && docker stop $DOCKER_CONTAINER_NAME && docker rm $DOCKER_CONTAINER_NAME && docker run -d -p $DOCKER_HOST_PORT:$PORT --name $DOCKER_CONTAINER_NAME $ECR_REPOSITORY:latest'
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main
